### PR TITLE
Removed redundant code.

### PR DESCRIPTION
**Pull request by mketab**
Removed redundant functions, refactored some variables and functions, reconfigured imports, adjusted circle size for ease of usabilty, remapped gray background control to `g`, removed redundant returns

### CODE REVIEW

**Review by Delafinn — COMMENTED** [review]
Don't see redundant code removed. Love the changes but will keep my original.

**Comment by mketab** [comment]
> Don't see redundant code removed. Love the changes but will keep my original.

image

All of the code above was removed because all the functions did were call another function.

**Comment by Delafinn** [comment]
If you don't mind opening a new pull request. I would like to take back what I said and push your changes. Sorry for being close-minded earlier.

**Comment by mketab** [comment]
You're all good, I don't think opening a new request is necessary, if you scroll down you should see an option to re-open the pull req :)

**Comment by Delafinn** [comment]
I did try that option but when hovering over reopen and commented. it looks like the repository that submitted this pull request has been deleted

**Comment by mketab** [comment]
I'll be sure to reopen it tomorrow, as I don't have access to my computer right now (GitHub iOS app is great)

**Comment by Delafinn** [comment]
Thank you!

**Pull request closed without merging**
